version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_USER: telegram_bot
      POSTGRES_PASSWORD: project
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
