name: InfoQ Parser Test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: corretto
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run InfoQ Parser Tests
        run: ./gradlew test --tests "org.example.parser.sites.InfoqParserUnitTest"